config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  
  namespace :api, defaults: { format: 'json' } do
    resources :kittens
  end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all 
  match "/422", to: "errors#unprocessable_content", via: :all 

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true,  numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 20 }
  validates :cuteness, :softness, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  def as_json(_options={})
      { :name => self.name,
        :cuteness => self.cuteness,
        :softness => self.softness
      }  
    end
end

app/controllers/api/kittens_controller.rb
module Api
  class KittensController < ApplicationController

    def index
      @kittens = Kitten.all
      respond_to do |format|
        format.json { render json: @kittens }
      end
    end

    def show
      @kitten = Kitten.find(params[:id])
      respond_to do |format|
        format.json { render json: @kitten }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status:404
  end

  def internal_server_error
    render status: 500
  end

  def unprocessable_content
    render states: 422
  end
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  # GET /kittens or /kittens.json
  def index
    @kittens = Kitten.all
  end

  # GET /kittens/1 or /kittens/1.json
  def show
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
  end

  # POST /kittens or /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to kitten_url(@kitten), notice: "Kitten was successfully created :)"
    else
      render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /kittens/1 or /kittens/1.json
  def update
    if @kitten.update(kitten_params)
      redirect_to kitten_url(@kitten), notice: "Kitten was successfully updated." 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /kittens/1 or /kittens/1.json
  def destroy
    @kitten.destroy

    redirect_to kittens_url, notice: "Kitten was destroyed :(" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div>
<%= form_with(model: kitten) do |form| %>
  <div class="flex flex-col">
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="py-2">
      <%= form.label :name, "Name:" %>
      <%= form.text_field :name, { class: 'rounded-lg border-2 border-teal-300 focus:border-teal-500 border-2 focus:outline-none focus:ring-0' } %>
    </div>

    <div class="py-2">
      <%= form.label :age, "Age:" %>
      <%= form.number_field :age, { in: 0..20, step: 1 , class: 'rounded-lg  border-2 border-teal-300 focus:border-teal-500 border-2 focus:outline-none focus:ring-0' }%>
    </div>

    <div class="py-2">
      <%= form.label :cuteness, "Cuteness:" %>
      <%= form.number_field :cuteness, { in: 1..10, step: 1, class: 'rounded-lg border-2 border-teal-300 focus:border-teal-500 border-2 focus:outline-none focus:ring-0' } %>
    </div>

    <div class="py-2">
      <%= form.label :softness, "Softness:" %>
      <%= form.number_field :softness,{ in: 1..10, step: 1, class: 'rounded-lg border-2 border-teal-300 focus:border-teal-500 border-2 focus:outline-none focus:ring-0' } %>
    </div>

    <%= form.submit({ class: 'cursor-pointer rounded-md border-2 border-black p-2' }) %>
  </div>
  </div>
<% end %>
</div>

app/views/kittens/_kitten.html.erb
<h1 class="text-4xl border-b-4">I am <span class="font-extrabold"><%= kitten.name %></span></h1>
<div id="<%= dom_id kitten %>" class="mt-3">
  <p>Age: <%= kitten.age %></p>
  <p>Cuteness: <%= kitten.cuteness %></p>
  <p>Softness: <%= kitten.softness %></p>
</div>

app/views/kittens/edit.html.erb
<div class="flex flex-col">
  <h1 class="text-4xl font-extrabold my-2">Editing kitten</h1>

  <div class="bg-zinc-50 bg-opacity-80 shadow-md px-5 py-10 rounded-md flex flex-col gap-2 items-start">
    <%= render "form", kitten: @kitten %>
    <%= link_to "Destroy", kitten_path(@kitten), { class: 'cursor-pointer rounded-md border-2 border-black p-2', data: {
      turbo_method: :delete,
      turbo_confirm: "Why would you want to destroy a kitten?!"
    } }%>
  </div>
  <div class="my-5 flex flex-col gap-1">
    <%= link_to "Show this kitten", @kitten, { class: 'underline decoration-2' } %>
    <%= link_to "Back to kittens", kittens_path, { class: 'underline decoration-2' } %>
  </div>
</div>

app/views/kittens/index.html.erb
<div class="grid grid-cols-1 lg:grid-cols-4">
  <div class="col-start-1 my-2">
    <h1 class="text-4xl font-extrabold">Kittens</h1>
    <%= link_to "Add a New kitten", new_kitten_path, { class: 'underline decoration-2 justify-self-center py-2' } %>
  </div>

  <div id="kittens" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 md:col-span-3 gap-4">
    <% @kittens.each do |kitten| %>
      <div class="rounded-md shadow-md bg-zinc-50 p-5 bg-opacity-80 flex flex-col justify-between gap-2">
        <div class="border-b-4 font-semibold text-lg"><%= kitten.name %></div>
        <div class="flex flex-col gap-1">
          <%= link_to "Details", kitten, { class: ' text-sm uppercase tracking-wider' } %>
          <span>
            <%= link_to "Edit", edit_kitten_path(kitten), { class: 'text-sm uppercase tracking-wider' } %> |
            <%= link_to "Destroy", kitten_path(kitten), { class: 'text-sm uppercase tracking-wider', data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure? This kitten will be lost forever."
                      } }%>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/kittens/new.html.erb
<div class="flex flex-col">
  <h1 class="text-4xl font-extrabold my-2">New kitten</h1>

  <div class="bg-gray-50 bg-opacity-60 px-5 py-10 rounded-md flex flex-col gap-2 items-start">
    <%= render "form", kitten: @kitten %>
  </div>

  <br>

  <div>
    <%= link_to "Back to kittens", kittens_path, { class: 'underline decoration-2' } %>
  </div>
</div>

app/views/kittens/show.html.erb
<div class="grid grid-cols-1 justify-center bg-zinc-50 bg-opacity-80 shadow-md p-10 rounded-md">
  <p class="text-emerald-500"><%= notice %></p>

  <%= render @kitten %>

  <div class="grid grid-cols-1">

    <div class="my-5 flex flex-col gap-2 items-start">
      <%= link_to "Edit this kitten", edit_kitten_path(@kitten), { class: 'cursor-pointer rounded-md border-2 border-black p-2' } %> 

      <%= link_to "Destroy", kitten_path(@kitten), { class: 'cursor-pointer rounded-md border-2 border-black p-2', data: {
              turbo_method: :delete,
              turbo_confirm: "Why would you want to destroy a kitten?!"
            } }%>
    </div>
    <%= link_to "Back to kittens", kittens_path, { class: 'underline decoration-2' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-teal-100 p-1 md:p-5 m-0">
    <main class="container mx-auto mt-5 md:px-5 flex flex-col justify-items-center items-center">
      <%= yield %>
    </main>
  </body>
</html>